package oopsystem.model;

import javafx.beans.property.*;
import java.time.LocalDateTime;

/**
 * Model class representing a single pass_slip table row.

 * Uses JavaFX Properties to stay consistent with Employee.java,
 * which also uses Property fields throughout the project.

 * Nullable DB columns (time_in, duration, status, file_path, destination)
 * are represented as plain Object types so they can hold null safely.
 */
public class PassSlip {

    private final IntegerProperty passSlipId;
    private final IntegerProperty employeeId;
    private final IntegerProperty issuedBy;
    private final StringProperty  reason;
    private final StringProperty  destination;
    private final StringProperty  filePath;

    // These are nullable — not wrapped in Property to keep null handling simple.
    private LocalDateTime timeIn;
    private LocalDateTime timeOut;
    private Integer       duration;
    private Boolean       status;

    // -------------------------------------------------------------------------
    // Constructor — used when issuing a NEW pass slip.
    // passSlipId excluded: auto-generated by PostgreSQL SERIAL.
    // timeIn / duration excluded: filled in when the employee returns.
    // status defaults to false (not yet returned).
    // -------------------------------------------------------------------------
    public PassSlip(
            int employeeId,
            int issuedBy,
            String reason,
            String destination,
            LocalDateTime timeOut) {

        this.passSlipId  = new SimpleIntegerProperty(0);
        this.employeeId  = new SimpleIntegerProperty(employeeId);
        this.issuedBy    = new SimpleIntegerProperty(issuedBy);
        this.reason      = new SimpleStringProperty(reason);
        this.destination = new SimpleStringProperty(destination);
        this.filePath    = new SimpleStringProperty(null);
        this.timeOut     = timeOut;
        this.status      = false;
    }

    // -------------------------------------------------------------------------
    // Constructor — used when READING an existing record from the database.
    // -------------------------------------------------------------------------

    public PassSlip(
            int passSlipId,
            int employeeId,
            int issuedBy,
            String reason,
            String destination,
            String filePath,
            LocalDateTime timeIn,
            LocalDateTime timeOut,
            Integer duration,
            Boolean status) {

        this.passSlipId  = new SimpleIntegerProperty(passSlipId);
        this.employeeId  = new SimpleIntegerProperty(employeeId);
        this.issuedBy    = new SimpleIntegerProperty(issuedBy);
        this.reason      = new SimpleStringProperty(reason);
        this.destination = new SimpleStringProperty(destination);
        this.filePath    = new SimpleStringProperty(filePath);
        this.timeIn      = timeIn;
        this.timeOut     = timeOut;
        this.duration    = duration;
        this.status      = status;
    }

    // -------------------------------------------------------------------------
    // Getters
    // -------------------------------------------------------------------------
    public int            getPassSlipId()  { return passSlipId.get();  }
    public int            getEmployeeId()  { return employeeId.get();  }
    public int            getIssuedBy()    { return issuedBy.get();    }
    public String         getReason()      { return reason.get();      }
    public String         getDestination() { return destination.get(); }
    public String         getFilePath()    { return filePath.get();    }
    public LocalDateTime  getTimeIn()      { return timeIn;            }
    public LocalDateTime  getTimeOut()     { return timeOut;           }
    public Integer        getDuration()    { return duration;          }
    public Boolean        getStatus()      { return status;            }

    // -------------------------------------------------------------------------
    // Setters — only fields that change AFTER issuance are mutable.
    // -------------------------------------------------------------------------
    public void setTimeIn(LocalDateTime timeIn)   { this.timeIn    = timeIn;    }
    public void setDuration(Integer duration)      { this.duration  = duration;  }
    public void setStatus(Boolean status)          { this.status    = status;    }
    public void setFilePath(String filePath)       { this.filePath.set(filePath);}
}